// ponytail: single source of truth cho tất cả message type string trong extension
export const MSG = {
  // State
  GET_STATE: "REVIEW_EXPORTER_GET_STATE",

  // TikTok
  START_BATCH: "REVIEW_EXPORTER_START_BATCH",
  RESUME_BATCH: "REVIEW_EXPORTER_RESUME_BATCH",
  PAUSE_BATCH: "REVIEW_EXPORTER_PAUSE_BATCH",
  CLEAR_STATE: "REVIEW_EXPORTER_CLEAR_STATE",
  EXPORT_XLSX: "REVIEW_EXPORTER_EXPORT_XLSX",
  EXPORT_CSV: "REVIEW_EXPORTER_EXPORT_CSV",
  COMMENT_API_RESPONSE: "REVIEW_EXPORTER_COMMENT_API_RESPONSE",
  COLLECT_COMMENTS: "REVIEW_EXPORTER_COLLECT_COMMENTS",

  // Shopee
  SHOPEE_SCRAPE: "REVIEW_EXPORTER_SHOPEE_SCRAPE",
  SHOPEE_PROGRESS: "REVIEW_EXPORTER_SHOPEE_PROGRESS",
  CLEAR_SHOPEE: "REVIEW_EXPORTER_CLEAR_SHOPEE",
  EXPORT_SHOPEE_XLSX: "REVIEW_EXPORTER_EXPORT_SHOPEE_XLSX",
  EXPORT_SHOPEE_CSV: "REVIEW_EXPORTER_EXPORT_SHOPEE_CSV",

  // Facebook
  FB_SCRAPE: "REVIEW_EXPORTER_FB_SCRAPE",
  FB_CLEAR: "REVIEW_EXPORTER_FB_CLEAR",
  FB_EXPORT_XLSX: "REVIEW_EXPORTER_FB_EXPORT_XLSX",
  FB_EXPORT_CSV: "REVIEW_EXPORTER_FB_EXPORT_CSV",
  FB_TRANSCRIPT_BATCH: "REVIEW_EXPORTER_FB_TRANSCRIPT_BATCH",
  FB_EXPORT_SRT: "REVIEW_EXPORTER_FB_EXPORT_SRT",
  FB_BATCH: "REVIEW_EXPORTER_FB_BATCH",
  FB_DONE: "REVIEW_EXPORTER_FB_DONE",
  FB_DEBUG: "REVIEW_EXPORTER_FB_DEBUG",
  FB_START_SCRAPE: "REVIEW_EXPORTER_FB_START_SCRAPE",

  // Instagram
  IG_TRANSCRIPT_BATCH: "REVIEW_EXPORTER_IG_TRANSCRIPT_BATCH",
  IG_EXPORT_SRT: "REVIEW_EXPORTER_IG_EXPORT_SRT",
  IG_CLEAR: "REVIEW_EXPORTER_IG_CLEAR",
  IG_EXPORT_XLSX: "REVIEW_EXPORTER_IG_EXPORT_XLSX",
  IG_EXPORT_CSV: "REVIEW_EXPORTER_IG_EXPORT_CSV",
};
